---
- name: Create a file
  hosts: all
#  vars:
#    ansible_python_interpreter: /usr/local/lib/python3
  gather_facts: no
  tasks:
    - name: Create a text file
      file:
        path: /home/file-by-ansible  # Specify the path where you want to create the file
        state: touch                     # Use 'touch' to create an empty file
