---
- name: Create file on all hosts
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes  # This allows the playbook to run with elevated privileges if necessary

  tasks:
    - name: Create file
      file:
        path: /home/k8s/test-ansible-123
        state: touch
